# Generated by Django 5.1.3 on 2024-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.FileField(blank=True, upload_to='productos/'),
        ),
    ]
